_:
  - &trigger
    trigger: commit
    branch: moonlight
  - &actions-use-spec
    fix-spec-file: []
    create-archive:
      - sh -c 'echo ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
    get-current-version:
      - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
  - &actions-rust2rpm
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm @${PACKIT_PROJECT_VERSION}'
  - &actions-rust2rpm-with-patch
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm -r @${PACKIT_PROJECT_VERSION}'

packages:
  moonlight-qt:
    paths: [ moonlight-qt ]
    specfile_path: moonlight-qt.spec
    downstream_package_name: moonlight-qt
    upstream_package_name: moonlight-qt
    actions: *actions-use-spec

targets:
  - fedora-rawhide
  - fedora-44

jobs:
  - job: copr_build
    owner: lecris
    project: moonlight
    <<: *trigger
#  - job: tests
#    <<: *trigger
