_:
  - &trigger
    trigger: commit
    branch: mctc-lib
  - &actions-use-spec
    fix-spec-file: []
    create-archive:
      - sh -c 'echo ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
    get-current-version:
      - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
  - &actions-rust2rpm
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm @${PACKIT_PROJECT_VERSION}'
  - &actions-rust2rpm-with-patch
    <<: *actions-use-spec
    fix-spec-file:
      - sh -c 'rust2rpm -r @${PACKIT_PROJECT_VERSION}'

packages:
  mctc-lib:
    paths: [ mctc-lib ]
    specfile_path: mctc-lib.spec
    downstream_package_name: mctc-lib
    upstream_package_name: mctc-lib
    actions: *actions-use-spec
  jonquil:
    paths: [ jonquil ]
    specfile_path: jonquil.spec
    downstream_package_name: jonquil
    upstream_package_name: jonquil
    actions: *actions-use-spec
  toml-f:
    paths: [ toml-f ]
    specfile_path: toml-f.spec
    downstream_package_name: toml-f
    upstream_package_name: toml-f
    actions: *actions-use-spec
  test-drive:
    paths: [ test-drive ]
    specfile_path: test-drive.spec
    downstream_package_name: test-drive
    upstream_package_name: test-drive
    actions: *actions-use-spec

targets:
  - fedora-rawhide

jobs:
  - job: copr_build
    owner: lecris
    project: mctc-lib
    <<: *trigger
#  - job: tests
#    <<: *trigger
